import type { ExerciseAnalysis, ExerciseId, GenericRep } from "./types";

// Rule-based, real-time coaching phrases — deliberately NOT generated by
// Gemini. A live rep needs its cue within a second or two of the moment it
// describes; an LLM round trip (seconds, and it needs several labeled
// images) cannot land in time. This is a separate, lighter-weight layer
// from src/lib/coaching.ts's post-set Gemini review: it reuses the same
// "in-person coach, not a hype-man" voice (terse, specific, no exclamation
// points, no praise that isn't tied to something just observed) but works
// entirely from the same local, deterministic measurements that already
// drive rep counting — nothing here is a numerical form judgment either.

export type LiveCue = { key: string; text: string };

function pick(pool: string[], index: number): string {
  return pool[index % pool.length];
}

// Approximate, exercise-specific "reasonably deep" and "reasonably paced"
// reference points for real-time nudges only. These are intentionally
// simpler than the post-set score/cue thresholds in library.ts (which stay
// the single source of truth for the score you see after analyzing a
// clip) — a live cue that is occasionally a little lenient or strict is
// far less costly than one that never arrives.
const DEPTH_REFERENCE: Partial<Record<ExerciseId, number>> = {
  squat: 100,
  pushup: 110,
  lunge: 100,
  deadlift: 140,
};
const MIN_DESCENT_SECONDS = 0.4;

const REP_GOOD_DEPTH = [
  "Good depth that rep.",
  "Nice range on that one.",
  "That depth looked solid.",
];
const REP_SHALLOW_DEPTH = [
  "Try to get a bit deeper next rep.",
  "You're cutting that one short — go a little further.",
  "A bit more range next time.",
];
const REP_TOO_FAST = [
  "Slow down on the way down.",
  "Control that descent a bit more.",
  "Take your time lowering into it.",
];
const DEADLIFT_KNEE_DRIFT = [
  "Keep the knee bend gentle — that's turning into a squat.",
  "Hinge at the hips more than the knees on that one.",
];
const HOLD_BROKEN = [
  "Straighten that line back out.",
  "Hips are drifting — reset the line.",
  "Bring your hips back in line.",
];
const HOLD_RECOVERED = [
  "Good, back in a straight line.",
  "That's it, line's straight again.",
];
const HOLD_MILESTONE = [
  "seconds — keep breathing.",
  "seconds, strong hold.",
  "seconds in, staying steady.",
];

export class LiveCoachTracker {
  private exercise: ExerciseId;
  private seenReps = 0;
  private lastFormOk: boolean | null = null;
  private lastMilestone = 0;
  private phraseCursor = 0;

  constructor(exercise: ExerciseId) {
    this.exercise = exercise;
  }

  reset(exercise: ExerciseId) {
    this.exercise = exercise;
    this.seenReps = 0;
    this.lastFormOk = null;
    this.lastMilestone = 0;
    this.phraseCursor = 0;
  }

  private next(pool: string[]): string {
    const phrase = pick(pool, this.phraseCursor);
    this.phraseCursor += 1;
    return phrase;
  }

  private repCue(rep: GenericRep, index: number): LiveCue {
    const depthReference = DEPTH_REFERENCE[this.exercise];
    const parts: string[] = [`Rep ${index + 1}.`];
    if (this.exercise === "deadlift" && rep.maxSecondary > 50) {
      parts.push(this.next(DEADLIFT_KNEE_DRIFT));
    } else if (depthReference !== undefined && rep.minPrimary > depthReference) {
      parts.push(this.next(REP_SHALLOW_DEPTH));
    } else if (rep.descent > 0 && rep.descent < MIN_DESCENT_SECONDS) {
      parts.push(this.next(REP_TOO_FAST));
    } else {
      parts.push(this.next(REP_GOOD_DEPTH));
    }
    return { key: `rep-${index}`, text: parts.join(" ") };
  }

  // Call with the latest recomputed analysis for the session so far. Returns
  // only newly-triggered cues (empty most of the time) by diffing against
  // what this tracker has already seen, so the caller can just speak
  // whatever comes back without tracking state itself.
  update(analysis: ExerciseAnalysis): LiveCue[] {
    const cues: LiveCue[] = [];
    if (analysis.mode === "cyclic" && analysis.reps) {
      for (let i = this.seenReps; i < analysis.reps.length; i += 1)
        cues.push(this.repCue(analysis.reps[i], i));
      this.seenReps = analysis.reps.length;
    } else if (analysis.mode === "hold" && analysis.hold) {
      const segments = analysis.hold.segments;
      const current = segments.at(-1);
      if (current) {
        if (this.lastFormOk === null) {
          this.lastFormOk = current.formOk;
        } else if (current.formOk !== this.lastFormOk) {
          cues.push({
            key: `form-${segments.length}`,
            text: current.formOk
              ? this.next(HOLD_RECOVERED)
              : this.next(HOLD_BROKEN),
          });
          this.lastFormOk = current.formOk;
        }
      }
      const goodSeconds = analysis.hold.totalGoodFormSeconds;
      const milestone = Math.floor(goodSeconds / 10) * 10;
      if (milestone > this.lastMilestone && milestone > 0) {
        this.lastMilestone = milestone;
        cues.push({
          key: `milestone-${milestone}`,
          text: `${milestone} ${this.next(HOLD_MILESTONE)}`,
        });
      }
    }
    return cues;
  }
}
